project_id = "xmwkwwkfjkrexgegghef"

[functions.send-contact-email]
verify_jwt = false

[functions.document-share-access]
verify_jwt = false

[functions.cron-weekly-digest]
verify_jwt = false

[functions.cron-monthly-financial-report]
verify_jwt = false